export { company, copyright, corporateFacts } from "./model/company";
export type { Company } from "./model/company";
export { milestones, milestonesByYear } from "./model/milestones";
export type { Milestone } from "./model/milestones";
export { principles } from "./model/principles";
export type { Principle } from "./model/principles";
export { differences, proofMetric } from "./model/strengths";
export type { Difference } from "./model/strengths";
export { founder } from "./model/founder";
export type { Founder, CredentialGroup } from "./model/founder";
export { team, teamSize } from "./model/team";
export type { Member } from "./model/team";
